#!/bin/sh

cd "$(dirname "$0")"

case $1 in
    ''|*[!0-9]*) 
    echo ""
    echo "ERROR: Invalid workspace number."
    echo ""
    echo "usage: wswitch <workspace number>"
	echo "You may change panel appearance images in folder:"
	echo "$HOME/.wswitch/" 
	echo ""
	;;
    *) 
    wmctrl -s $1

	IMGNAME="$HOME/.wswitch/bckgnd$1.png"

	xfconf-query -c xfce4-panel -p /panels/panel-0/background-image -s $IMGNAME
	xfconf-query -c xfce4-panel -p /panels/panel-0/background-style -s 0
	xfconf-query -c xfce4-panel -p /panels/panel-0/background-style -s 2
    ;;
esac


